name: Build APK (Expo EAS)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo and EAS
        run: |
          npm install -g expo-cli eas-cli

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build APK with EAS
        run: |
          eas build -p android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
